version: '3.5'
services:
  fugu:
    image: ubuntu:18.04
    restart: always
    working_dir: /fugu
    volumes:
      - ./fugu:/fugu
    ports:
      - 18181:8090
    command: ./fugu dev.yaml
    # network_mode: host
    networks:
      compose_network:
        ipv4_address: ${COMPOSE_NETWORK_PREFIX}.11
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d/
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER= root
      - MYSQL_PASSWORD= 123456
      - MYSQL_ROOT_PASSWORD= 123456
      - MYSQL_ROOT_HOST= %
    networks:
      compose_network:
        ipv4_address: ${COMPOSE_NETWORK_PREFIX}.12
  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - './redis/data:/data'
    ports:
      - 16379:6379
    networks:
      compose_network:
        ipv4_address: ${COMPOSE_NETWORK_PREFIX}.13
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 10080:80
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/static_files/dist
    networks:
      compose_network:
        ipv4_address: ${COMPOSE_NETWORK_PREFIX}.14
networks:
  compose_network:
    external: true
    name: ${COMPOSE_NETWORK}
