///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package secrets

import (
	"fmt"
	"time"

	"FuguBackend/app/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *Secrets {
	return new(Secrets)
}

func NewQueryBuilder() *secretsQueryBuilder {
	return new(secretsQueryBuilder)
}

func (t *Secrets) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type secretsQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *secretsQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *secretsQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&Secrets{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *secretsQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&Secrets{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *secretsQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&Secrets{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *secretsQueryBuilder) First(db *gorm.DB) (*Secrets, error) {
	ret := &Secrets{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *secretsQueryBuilder) QueryOne(db *gorm.DB) (*Secrets, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *secretsQueryBuilder) QueryAll(db *gorm.DB) ([]*Secrets, error) {
	var ret []*Secrets
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *secretsQueryBuilder) Limit(limit int) *secretsQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *secretsQueryBuilder) Offset(offset int) *secretsQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *secretsQueryBuilder) WhereId(p mysql.Predicate, value int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereIdIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereIdNotIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderById(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereCreatedAt(p mysql.Predicate, value time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereCreatedAtIn(value []time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByCreatedAt(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereUpdatedAt(p mysql.Predicate, value time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereUpdatedAtIn(value []time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByUpdatedAt(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereDeletedAt(p mysql.Predicate, value time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereDeletedAtIn(value []time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereDeletedAtNotIn(value []time.Time) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByDeletedAt(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deleted_at "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereSecretId(p mysql.Predicate, value int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "secret_id", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereSecretIdIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "secret_id", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereSecretIdNotIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "secret_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderBySecretId(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "secret_id "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereAuthorId(p mysql.Predicate, value int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "author_id", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereAuthorIdIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "author_id", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereAuthorIdNotIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "author_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByAuthorId(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "author_id "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereViewLevel(p mysql.Predicate, value int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "view_level", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereViewLevelIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "view_level", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereViewLevelNotIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "view_level", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByViewLevel(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "view_level "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereTimestamp(p mysql.Predicate, value int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "timestamp", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereTimestampIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "timestamp", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereTimestampNotIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "timestamp", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByTimestamp(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "timestamp "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereViews(p mysql.Predicate, value int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "views", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereViewsIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "views", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereViewsNotIn(value []int64) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "views", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByViews(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "views "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereContent(p mysql.Predicate, value string) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereContentIn(value []string) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereContentNotIn(value []string) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "content", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByContent(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "content "+order)
	return qb
}

func (qb *secretsQueryBuilder) OrderBy(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, " "+order)
	return qb
}

func (qb *secretsQueryBuilder) WhereStatus(p mysql.Predicate, value int32) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereStatusIn(value []int32) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) WhereStatusNotIn(value []int32) *secretsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *secretsQueryBuilder) OrderByStatus(asc bool) *secretsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}
