[cmd]
genTables = ''

[common]
version = "0.0.1"
is_debug = false
log_level = "info"
log_path = "./logs/fugu.log"
start_time = "2023-11-01"

[ser]
addr = "127.0.0.1:9999"

[mysql]

    [mysql.base]
        connmaxlifetime = 60
        maxidleconn = 60
        maxopenconn = 10
        loglevel = "info"

    [mysql.read]
        host = "127.0.0.1"
        port = "13306"
        database = "fugu"
        pass = "123456"
        user = "root"

    [mysql.write]
        host = "127.0.0.1"
        port = "13306"
        database = "fugu"
        pass = "123456"
        user = "root"
[redis]
addr = "127.0.0.1:16379"
db = 0
maxretries = 3
minidleconns = 5
pass = ""
poolsize = 10

[etcd]
host1 = "94.74.73.195:20000"
host2 = "94.74.73.195:20002"
host3 = "94.74.73.195:20004"

[aws]
bucket = "fugutoxic"
access_key = "AKIASDITKHMUVGS5XGHB"
secret_key = "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"
region = "ap-northeast-1"
endpoint = "https://s3.ap-northeast-1.amazonaws.com/"

[jwt]
issuer = "fuguclub.io"
secret_key = "hp"
expiration_time = 86400

[twitter]
access_key = "AAAAAAAAAAAAAAAAAAAAAOcMhQEAAAAAv7AxXoCTM5%2BdfFUhcaOS3TLvWzM%3DMgLOp3wGhKlah2N9fitsuECrcD2gjk1tku6NZgXKFOgE4yrVyJ"


[hashids]
length = 12
secret = "6ab6122836cfef95f8db"

[language]
local = "zh-cn"


[mail]
host = "smtp.163.com"
pass = ""
port = 465
to = ""
user = ""