///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package nfts

import (
	"fmt"

	"FuguBackend/app/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *Nfts {
	return new(Nfts)
}

func NewQueryBuilder() *nftsQueryBuilder {
	return new(nftsQueryBuilder)
}

func (t *Nfts) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type nftsQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *nftsQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *nftsQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&Nfts{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *nftsQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&Nfts{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *nftsQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&Nfts{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *nftsQueryBuilder) First(db *gorm.DB) (*Nfts, error) {
	ret := &Nfts{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *nftsQueryBuilder) QueryOne(db *gorm.DB) (*Nfts, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *nftsQueryBuilder) QueryAll(db *gorm.DB) ([]*Nfts, error) {
	var ret []*Nfts
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *nftsQueryBuilder) Limit(limit int) *nftsQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *nftsQueryBuilder) Offset(offset int) *nftsQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *nftsQueryBuilder) WhereId(p mysql.Predicate, value int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereIdIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereIdNotIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderById(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereCreatedAt(p mysql.Predicate, value time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereCreatedAtIn(value []time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByCreatedAt(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereUpdatedAt(p mysql.Predicate, value time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereUpdatedAtIn(value []time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByUpdatedAt(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereDeletedAt(p mysql.Predicate, value time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereDeletedAtIn(value []time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereDeletedAtNotIn(value []time.Time) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByDeletedAt(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deleted_at "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereUserId(p mysql.Predicate, value int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "user_id", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereUserIdIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "user_id", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereUserIdNotIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "user_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByUserId(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "user_id "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereChainId(p mysql.Predicate, value int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "chain_id", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereChainIdIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "chain_id", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereChainIdNotIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "chain_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByChainId(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "chain_id "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereTokenId(p mysql.Predicate, value int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "token_id", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereTokenIdIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "token_id", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereTokenIdNotIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "token_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByTokenId(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "token_id "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereAddress(p mysql.Predicate, value string) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "address", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereAddressIn(value []string) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "address", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereAddressNotIn(value []string) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "address", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByAddress(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "address "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereUserid(p mysql.Predicate, value int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "userid", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereUseridIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "userid", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereUseridNotIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "userid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByUserid(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "userid "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereChainid(p mysql.Predicate, value int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "chainid", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereChainidIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "chainid", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereChainidNotIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "chainid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByChainid(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "chainid "+order)
	return qb
}

func (qb *nftsQueryBuilder) WhereTokenid(p mysql.Predicate, value int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "tokenid", p),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereTokenidIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "tokenid", "IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) WhereTokenidNotIn(value []int64) *nftsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "tokenid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *nftsQueryBuilder) OrderByTokenid(asc bool) *nftsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "tokenid "+order)
	return qb
}
