///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package friends

import (
	"fmt"

	"FuguBackend/app/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *Friends {
	return new(Friends)
}

func NewQueryBuilder() *friendsQueryBuilder {
	return new(friendsQueryBuilder)
}

func (t *Friends) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type friendsQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *friendsQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *friendsQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&Friends{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *friendsQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&Friends{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *friendsQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&Friends{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *friendsQueryBuilder) First(db *gorm.DB) (*Friends, error) {
	ret := &Friends{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *friendsQueryBuilder) QueryOne(db *gorm.DB) (*Friends, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *friendsQueryBuilder) QueryAll(db *gorm.DB) ([]*Friends, error) {
	var ret []*Friends
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *friendsQueryBuilder) Limit(limit int) *friendsQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *friendsQueryBuilder) Offset(offset int) *friendsQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *friendsQueryBuilder) WhereId(p mysql.Predicate, value int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereIdIn(value []int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereIdNotIn(value []int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) OrderById(asc bool) *friendsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *friendsQueryBuilder) WhereCreatedAt(p mysql.Predicate, value time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereCreatedAtIn(value []time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) OrderByCreatedAt(asc bool) *friendsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *friendsQueryBuilder) WhereUpdatedAt(p mysql.Predicate, value time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereUpdatedAtIn(value []time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) OrderByUpdatedAt(asc bool) *friendsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *friendsQueryBuilder) WhereDeletedAt(p mysql.Predicate, value time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", p),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereDeletedAtIn(value []time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereDeletedAtNotIn(value []time.Time) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) OrderByDeletedAt(asc bool) *friendsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deleted_at "+order)
	return qb
}

func (qb *friendsQueryBuilder) WhereBaseId(p mysql.Predicate, value int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "base_id", p),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereBaseIdIn(value []int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "base_id", "IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereBaseIdNotIn(value []int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "base_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) OrderByBaseId(asc bool) *friendsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "base_id "+order)
	return qb
}

func (qb *friendsQueryBuilder) WhereFriendId(p mysql.Predicate, value int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "friend_id", p),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereFriendIdIn(value []int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "friend_id", "IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereFriendIdNotIn(value []int64) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "friend_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) OrderByFriendId(asc bool) *friendsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "friend_id "+order)
	return qb
}

func (qb *friendsQueryBuilder) WhereStatus(p mysql.Predicate, value int32) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereStatusIn(value []int32) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) WhereStatusNotIn(value []int32) *friendsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *friendsQueryBuilder) OrderByStatus(asc bool) *friendsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}
